### ISSUE TITLE
bug:feature: conversor: api demonstrada pede key

### ISSUE THREAD

**Issue by vzsoares** [podcodar/projects#5]
> estou criando essa issue para poder me referir a mesma no PR

**Comment by marco-souza** [comment]
Bem lembrado Zenha! A API antigamente era free, mas agora ta cobrando.Precisamos achar uma API free.

**Comment by vzsoares** [comment]
> Bem lembrado Zenha! A API antigamente era free, mas agora ta cobrando.Precisamos achar uma API free.

Fiz um PR resolvendo esse problema !

   Pr #6
